version: '3.7'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8500:8500"
    restart: on-failure
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  
  
  mysql-backend:
     image: mysql:8.0.19
     environment:
        # MYSQL_USER: root
       MYSQL_PASSWORD: fakultet
       MYSQL_DATABASE: xml_backend
     ports:
       - "3306"  
     restart: always  
     container_name: mysql-backend
     networks:
       - static-network  
     volumes:
       - mysql-data:/var/lib/mysql  
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     depends_on:
       - consul-server

  
  user-services:
     image: user-services
     environment:
         DATABASE_USERNAME: root
         DATABASE_PASSWORD: fakultet
         DATABASE_SCHEMA: user_services
         DATABASE_DOMAIN: mysql-backend
         DATABASE_PORT: 3306
     build:
      context: ./services/user-services
      dockerfile: Dockerfile
     tty: true
     networks:
      - static-network
     restart: on-failure
     depends_on:
       - consul-server
       - mysql-backend

  media-services:
     image: media-services
     environment:
         DATABASE_USERNAME: root
         DATABASE_PASSWORD: fakultet
         DATABASE_SCHEMA: media_services
         DATABASE_DOMAIN: mysql-backend
         DATABASE_PORT: 3306
     build:
      context: ./services/media-services
      dockerfile: Dockerfile
     tty: true
     networks:
      - static-network
     restart: on-failure
     depends_on:
      - consul-server
      - mysql-backend

  handlingreq-services:
     image: handlingreq-services
     environment:
         DATABASE_USERNAME: root
         DATABASE_PASSWORD: fakultet
         DATABASE_SCHEMA: handlingreq_services
         DATABASE_DOMAIN: mysql-backend
         DATABASE_PORT: 3306
     build:
      context: ./services/handlingReq-services
      dockerfile: Dockerfile
     tty: true
     networks:
      - static-network
     restart: on-failure
     depends_on:
      - consul-server
      - mysql-backend

  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    networks:
      - static-network
    restart: on-failure
    depends_on:
      - consul-server
      


volumes:
  mysql-data:
  
  
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16